# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Test BL
  inputs:
    command: test
    projects: 'Yahtzee.BL.Test/Yahtzee.BL.Test.csproj'
    arguments: '--configuration Debug'    

- task: DotNetCoreCLI@2
  displayName: Test PL
  inputs:
    command: test
    projects: 'Yahtzee.PL.Test/Yahtzee.PL.Test.csproj'
    arguments: '--configuration Debug' 