CREATE TABLE [dbo].[tblActivation]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [LobbyId] UNIQUEIDENTIFIER NOT NULL, 
    [KeyCode] VARCHAR(10) NOT NULL, 
    [StartDate] DATETIME NOT NULL, 
    [EndDate] DATETIME NOT NULL
)
